# Generated by Django 2.1.3 on 2019-06-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='issueID',
        ),
    ]
